### PR TITLE
Fixing compilation, choosing a single runtime (node, not bun)

### PR DESCRIPTION
**Pull request by elmerbulthuis**
Lot's of fixes in the compilation setup. Notable changes are:
- only use one runtime, node
- all source files should be in the `src` directory (not also in a `__test__` directory)
- tests that use the data base should be run in the withDatabase wrapper
- when running tests that require a database, run `docker-compose up` first and set the PGURI environment variable
- if the PGURI variable is not set, then db tests will pass! we do want to show a warning or something when this happens. Be aware of this!
- compilation will also compile dependent projects
- running test files from the workspace will automatically trigger compilation
- running tests from pnpm will also compile typescript first
- packaging a package will also trigger compilation first
- compilation is incremental (and quite fast) via the compound setting. This will produce a .tsbuildinfo file. Don't touch it, don't check it in. you may delete it
- packages have exactly one export, this is the main.ts file, if other exports are allowed, lets discuss
- node test framework is used with node assertions. Another assertion library could be used
- typescript files are using modules, output is javascript in commonjs (currently required for opentelemetry)
- import files by their js name, so: `import "./file.js", not `import "./file"` or `import "./file.ts"`

### CODE REVIEW

**Comment by elmerbulthuis** [comment]
db tests are currently failing, let's discuss

**Comment by elmerbulthuis** [comment]
> db tests are currently failing, let's discuss

eh ye so those tests (one test tbh) fail because of a mismatch in the way the database is setup, the approach that is used now is setup to use no globals. The database service (core) is setup to use a global db connection. This mismatch should be solved but how?

Do we do globals or non-globals. I personally have a large bias in favor of the non global approach. this is because this is easier to debug, more stable in testing, more flexible and it gives complete control over the connections. But ofcourse globals is also an option. this needs some discussoin!

**Comment by mgm1313** [comment]
Thanks for your work! We’ve discussed some points via Discord already, but to keep everything documented:

### Non-global DB Instance
I'm also in favor of _not_ using a global db instance. However, I want to avoid passing a db object to every single function inside the core package (e.g., https://github.com/buchungapp/nationaal-watersportdiploma/blob/main/packages/core/src/curriculum/index.ts). 
I see two options:

- Utilizing the `async_hooks` context, similar to how we handle transactions. This would make the consumer of the core package responsible for providing a top-level db context. We're limited to runtimes that support async_hooks, but I don't see this as a drawback since we're not aiming to support multiple runtimes.
- Refactoring the core package to export classes instead of individual functions, allowing the class instance to maintain the db instance. This approach might lead to larger classes, which we’ve found to be cumbersome to break down at Buchung.

### Testing
I haven’t settled on a testing approach yet (this might require a separate discussion). It’s unlikely we’ll use the docker-compose image for database testing, as we need the full Supabase environment for most checks. For instance, the default Supabase PostgreSQL image doesn’t include their default schemas, causing the initial migration of Drizzle to fail. Moreover, most tests depend on Supabase auth, necessitating the auth server to be operational. Currently, I spin up a local Supabase instance via supabase start, which is also feasible in CI environments: https://supabase.com/docs/guides/functions/cicd-workflow

**Comment by elmerbulthuis** [comment]
also checkout this -> https://github.com/buchungapp/nationaal-watersportdiploma/pull/110

**Comment by elmerbulthuis** [comment]
ye testing is a differnt discussion, but i guess one of the requirements should be that testing can be done locally.

**Comment by elmerbulthuis** [comment]
async hooks could be used for a non-global db instance or transaction. Could be something like:

```ts
await using context.database();

const list = await getListOfSomething();
// do something with that data
```
or
```ts
await using context.databaseTransaction();

const list = await getListOfSomething();
// do something with that data, in a transaction
```

Transactoins / db connections could also be made implicit.

**Comment by elmerbulthuis** [comment]
close by https://github.com/buchungapp/nationaal-watersportdiploma/pull/111

**Pull request closed without merging**
